# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imputDecKeyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_impDecKeyDialog(object):
    def setupUi(self, saveDialog):
        saveDialog.setObjectName("saveDialog")
        saveDialog.resize(406, 122)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(saveDialog.sizePolicy().hasHeightForWidth())
        saveDialog.setSizePolicy(sizePolicy)
        saveDialog.setMinimumSize(QtCore.QSize(406, 120))
        saveDialog.setMaximumSize(QtCore.QSize(406, 122))
        saveDialog.setStyleSheet("background-color: rgb(205, 255, 252);")
        self.verticalLayout = QtWidgets.QVBoxLayout(saveDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(saveDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.imputDecryptionkeyLineEdit = QtWidgets.QLineEdit(self.frame)
        self.imputDecryptionkeyLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imputDecryptionkeyLineEdit.setObjectName("imputDecryptionkeyLineEdit")
        self.verticalLayout_2.addWidget(self.imputDecryptionkeyLineEdit)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(saveDialog)
        self.buttonBox.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(94, 239, 255);\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(saveDialog)
        self.buttonBox.accepted.connect(saveDialog.accept)
        self.buttonBox.rejected.connect(saveDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(saveDialog)

    def retranslateUi(self, saveDialog):
        _translate = QtCore.QCoreApplication.translate
        saveDialog.setWindowTitle(_translate("saveDialog", "Decryption key imput"))
        self.label_3.setText(_translate("saveDialog", "Decryption key:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    impDecKeyDialog = QtWidgets.QDialog()
    ui = Ui_impDecKeyDialog()
    ui.setupUi(impDecKeyDialog)
    impDecKeyDialog.show()
    sys.exit(app.exec_())
