# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saveasDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_saveDialog(object):
    def setupUi(self, saveDialog):
        saveDialog.setObjectName("saveDialog")
        saveDialog.resize(406, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(saveDialog.sizePolicy().hasHeightForWidth())
        saveDialog.setSizePolicy(sizePolicy)
        saveDialog.setMinimumSize(QtCore.QSize(406, 230))
        saveDialog.setMaximumSize(QtCore.QSize(406, 260))
        saveDialog.setStyleSheet("background-color: rgb(205, 255, 252);")
        self.verticalLayout = QtWidgets.QVBoxLayout(saveDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(saveDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 30)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.SiteLineEdit = QtWidgets.QLineEdit(self.frame)
        self.SiteLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SiteLineEdit.setObjectName("SiteLineEdit")
        self.verticalLayout_2.addWidget(self.SiteLineEdit)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.usernameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout_2.addWidget(self.usernameLineEdit)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.decryptionkeyLineEdit = QtWidgets.QLineEdit(self.frame)
        self.decryptionkeyLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.decryptionkeyLineEdit.setObjectName("decryptionkeyLineEdit")
        self.verticalLayout_2.addWidget(self.decryptionkeyLineEdit)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(saveDialog)
        self.buttonBox.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(94, 239, 255);\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(saveDialog)
        self.buttonBox.accepted.connect(saveDialog.accept)
        self.buttonBox.rejected.connect(saveDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(saveDialog)

    def retranslateUi(self, saveDialog):
        _translate = QtCore.QCoreApplication.translate
        saveDialog.setWindowTitle(_translate("saveDialog", "Save as:"))
        self.label_2.setText(_translate("saveDialog", "Site:"))
        self.label.setText(_translate("saveDialog", "Username or email:"))
        self.label_3.setText(_translate("saveDialog", "Decryption key:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    saveDialog = QtWidgets.QDialog()
    ui = Ui_saveDialog()
    ui.setupUi(saveDialog)
    saveDialog.show()
    sys.exit(app.exec_())
